### ISSUE TITLE
/trade doesn't work

### ISSUE THREAD

**Issue by Tanimsiz** [CodingAir/TradeSystem#100]
After i update trade system to 1.1.0, that happens every /trade command use.
Paper 1.11.2
Java 1.8.0_191
```

[20:49:41] [Server thread/INFO]: Stalin issued server command: /trade kerjkl
[20:49:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trade' in plugin TradeSystem v1.1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paper.jar:git-Paper-1104]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[paper.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393) ~[paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198) ~[paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paper.jar:git-Paper-1104]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [paper.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at de.codingair.tradesystem.trade.commands.TradeCMD.request(TradeCMD.java:310) ~[?:?]
	at de.codingair.tradesystem.trade.commands.TradeCMD$7.runCommand(TradeCMD.java:208) ~[?:?]
	at de.codingair.codingapi.server.commands.MultiCommandComponent.runCommand(MultiCommandComponent.java:27) ~[?:?]
	at de.codingair.codingapi.server.commands.CommandBuilder.onCommand(CommandBuilder.java:145) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paper.jar:git-Paper-1104]
	... 15 more

```

**Comment by CodingAir** [comment]
Thank you, I'm gonna check this.

**Comment by CodingAir** [comment]
Sorry for the late respond.
Do you changed the Language.yml?

**Comment by Tanimsiz** [comment]
Yes, I changed.

**Comment by CodingAir** [comment]
Can you send me your Language.yml?

**Comment by Tanimsiz** [comment]
Where can i pm you?

**Comment by CodingAir** [comment]
Discord. My name is CodingAir#0281

**Comment by Tanimsiz** [comment]
Message sent at Last Tuesday at 01:21

**Comment by CodingAir** [comment]
I haven't received a friend request. What's your name?
