### ISSUE TITLE
TradeSystem null pointer

### ISSUE THREAD

**Issue by N0tMyFaultOG** [CodingAir/TradeSystem#132]
I just noticed the following null pointer by checking my console. Not sure how to reproduce it but maybe something you want to look into:

````
[16:39:50 WARN]: [TradeSystem] Task #6718781 for TradeSystem v1.1.4 generated an exception
java.lang.NullPointerException: null
at de.codingair.codingapi.player.gui.inventory.gui.GUI.lambda$confirmClosing$0(GUI.java:221) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by CodingAir** [comment]
Thank you!
