### ISSUE TITLE
Attempting to trade with offline players results in stacktrace

### ISSUE THREAD

**Issue by N0tMyFaultOG** [CodingAir/TradeSystem#134]
If you attempt to insert the name of an offline player after `/trade`, it will result in the following stacktrace rather than telling the person that you cannot trade with offline players.

```
>[01:47:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trade' in plugin TradeSystem v1.1.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[?:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[?:git-Paper-62]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1166) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at de.codingair.tradesystem.trade.commands.TradeCMD.request(TradeCMD.java:224) ~[?:?]
at de.codingair.tradesystem.trade.commands.TradeCMD$7.runCommand(TradeCMD.java:207) ~[?:?]
at de.codingair.codingapi.server.commands.builder.MultiCommandComponent.runCommand(MultiCommandComponent.java:27) ~[?:?]
at de.codingair.codingapi.server.commands.builder.CommandBuilder.onCommand(CommandBuilder.java:238) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.1.jar:git-Paper-62]
... 17 more
```

**Comment by N0tMyFaultOG** [comment]
Heyo,

are there any plans to fix the current issues?

**Comment by CodingAir** [comment]
Yep, I'm on it right now. ETA: Today
