### ISSUE TITLE
Timout Exception

### ISSUE THREAD

**Issue by CodingAir** [CodingAir/TradeSystem#212]
**Contact: [Ask3r](https://www.spigotmc.org/members/ask3r.324608/)**
```
[12:29:20 WARN]: [TradeSystem] Task #591 for TradeSystem v1.2.1 generated an exception
java.lang.NullPointerException: null
        at de.codingair.tradesystem.trade.commands.TradeCMD$9.timeout(TradeCMD.java:336) ~[?:?]
        at de.codingair.tradesystem.trade.commands.TradeCMD$9.timeout(TradeCMD.java:333) ~[?:?]
        at de.codingair.codingapi.tools.time.TimeSet.lambda$onSecond$0(TimeSet.java:44) ~[?:?]
        at java.util.Collection.removeIf(Collection.java:544) ~[?:?]
        at de.codingair.codingapi.tools.time.TimeSet.onSecond(TimeSet.java:41) ~[?:?]
        at de.codingair.codingapi.API$2.run(API.java:168) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by CodingAir** [comment]
Fixed with #214
