### ISSUE TITLE
Economy error after finishing the Trade Even when Economy is disabled

### ISSUE THREAD

**Issue by CodingAir** [CodingAir/TradeSystem#240]
Economy error after finishing the Trade even when Economy is disabled.

Moving exp to the first place in the priority list fixes this issue.

**Comment by CodingAir** [comment]
Error:
```
[12:14:09 ERROR]: Could not pass event InventoryClickEvent to TradeSystem v1.2.1_Hotfix-2
java.lang.NullPointerException: null
        at de.codingair.tradesystem.utils.money.adapters.Vault.getMoney(Vault.java:18) ~[?:?]
        at de.codingair.tradesystem.utils.Profile.getMoney(Profile.java:18) ~[?:?]
        at de.codingair.tradesystem.trade.Trade.finish(Trade.java:289) ~[?:?]
        at de.codingair.tradesystem.trade.Trade.update(Trade.java:101) ~[?:?]
        at de.codingair.tradesystem.trade.TradingGUI$3.onClick(TradingGUI.java:444) ~[?:?]
        at de.codingair.tradesystem.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:266) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor981.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-966]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2638) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1199) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1175) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1019) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[12:14:09 WARN]: [TradeSystem] Task #2372 for TradeSystem v1.2.1_Hotfix-2 generated an exception
java.lang.NullPointerException: null
        at de.codingair.tradesystem.utils.money.adapters.Vault.getMoney(Vault.java:18) ~[?:?]
        at de.codingair.tradesystem.utils.Profile.getMoney(Profile.java:18) ~[?:?]
        at de.codingair.tradesystem.trade.Trade.finish(Trade.java:289) ~[?:?]
        at de.codingair.tradesystem.trade.Trade.update(Trade.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
