### ISSUE TITLE
Concurrency exceptions with no players online

### ISSUE THREAD

**Issue by Dynitios** [CodingAir/TradeSystem#307]
**Describe the bug**
Hey. My server has been having some issues where I have to restart it every couple hours to prevent heavy lagspikes and eventually a crash. Not yet sure what the problem is, but tonight I just let the server run the entire night to see what would happen. I encountered a couple concurrency Exceptions in TradeSystem while no players were online.

Stacktrace:
```
[01:12:52] [Craft Scheduler Thread - 270/WARN]: [TradeSystem] Plugin TradeSystem v2.0.2 generated an exception while executing task 396
java.lang.IllegalMonitorStateException: null
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1006) ~[?:?]
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494) ~[?:?]
	at de.codingair.tradesystem.lib.codingapi.tools.time.TimeMap.onSecond(TimeMap.java:57) ~[?:?]
	at de.codingair.tradesystem.lib.codingapi.API$2.lambda$run$0(API.java:171) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706) ~[?:?]
	at de.codingair.tradesystem.lib.codingapi.API$2.run(API.java:169) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-46]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-46]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-46]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

The same exception followed three times later that night.

Like I said, not yet sure if TradeSystem is causing this lag/crashes, or the lag caused these exceptions. Thought I'd report it either way.

**To Reproduce**
Unsure how to reproduce it. Could be caused by the server running more than 400 ticks behind for long periods of time.

**Expected behavior**
No exceptions, especially when no players are online.

**Discord contact**: Dynition#3434

**Comment by CodingAir** [comment]
I'll wait for further information since I can't find any issues in the code.
