### ISSUE TITLE
When trading it counts down to one and then stops.

### ISSUE THREAD

**Issue by BomberDavi** [CodingAir/TradeSystem#314]
Here is the consle logs,
![2021-07-08_15 16 56](https://user-images.githubusercontent.com/87152270/124992647-7b688000-e000-11eb-88a7-2e51d5130311.png)
```
08.07 21:18:40 [Server] Server thread/INFO BomberDavi issued server command: /trade BlueJello05
08.07 21:18:54 [Server] Server thread/INFO BlueJello05 issued server command: /trade accept BomberDavi
08.07 21:18:56 [Server] Server thread/INFO CONSOLE issued server command: /list 
08.07 21:18:56 [Server] Server thread/INFO There are 2 out of maximum 20 players online.
08.07 21:18:56 [Server] Server thread/INFO default: BlueJello05, BomberDavi
08.07 21:19:07 [Server] Server thread/WARN Task #2400 for TradeSystem v2.0.2 generated an exception
08.07 21:19:07 [Server] INFO java.lang.NoSuchMethodError: com.earth2me.essentials.api.Economy.playerExists(Ljava/util/UUID;)Z
08.07 21:19:07 [Server] INFO at de.codingair.tradesystem.spigot.trade.layout.types.impl.economy.money.essentials.EssentialsIcon.check(EssentialsIcon.java:59) ~[?:?]
08.07 21:19:07 [Server] INFO at de.codingair.tradesystem.spigot.trade.layout.types.impl.economy.money.essentials.EssentialsIcon.getPlayerValue(EssentialsIcon.java:26) ~[?:?]
08.07 21:19:07 [Server] INFO at de.codingair.tradesystem.spigot.trade.layout.types.impl.economy.EconomyIcon.tryFinish(EconomyIcon.java:166) ~[?:?]
08.07 21:19:07 [Server] INFO at de.codingair.tradesystem.spigot.trade.Trade.tryFinish(Trade.java:110) ~[?:?]
08.07 21:19:07 [Server] INFO at de.codingair.tradesystem.spigot.trade.BukkitTrade.lambda$finish$0(BukkitTrade.java:250) ~[?:?]
08.07 21:19:07 [Server] INFO at de.codingair.tradesystem.spigot.trade.BukkitTrade$2.run(BukkitTrade.java:356) ~[?:?]
08.07 21:19:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
08.07 21:19:08 [Server] Server thread/WARN Task #2400 for TradeSystem v2.0.2 generated an exception
08.07 21:19:08 [Server] INFO java.lang.NoSuchMethodError: com.earth2me.essentials.api.Economy.playerExists(Ljava/util/UUID;)Z
08.07 21:19:08 [Server] INFO at de.codingair.tradesystem.spigot.trade.layout.types.impl.economy.money.essentials.EssentialsIcon.check(EssentialsIcon.java:59) ~[?:?]
08.07 21:19:08 [Server] INFO at de.codingair.tradesystem.spigot.trade.layout.types.impl.economy.money.essentials.EssentialsIcon.getPlayerValue(EssentialsIcon.java:26) ~[?:?]
08.07 21:19:08 [Server] INFO at de.codingair.tradesystem.spigot.trade.layout.types.impl.economy.EconomyIcon.tryFinish(EconomyIcon.java:166) ~[?:?]
08.07 21:19:08 [Server] INFO at de.codingair.tradesystem.spigot.trade.Trade.tryFinish(Trade.java:110) ~[?:?]
08.07 21:19:08 [Server] INFO at de.codingair.tradesystem.spigot.trade.BukkitTrade.lambda$finish$0(BukkitTrade.java:250) ~[?:?]
08.07 21:19:08 [Server] INFO at de.codingair.tradesystem.spigot.trade.BukkitTrade$2.run(BukkitTrade.java:356) ~[?:?]
08.07 21:19:08 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:08 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:08 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:08 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:08 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:08 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
08.07 21:19:08 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot_Latest_1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
```

**Comment by CodingAir** [comment]
Which version of Essentials do you use?

**Comment by BomberDavi** [comment]
2.7.20

> Which version of Essentials do you use?

**Comment by BomberDavi** [comment]
> 2.7.20
> 
> > Which version of Essentials do you use?

2.17.20*

**Comment by CodingAir** [comment]
Using the latest version of EssentialsX should solve this issue.
