### ISSUE TITLE
/tradelog <player> doesn't work

### ISSUE THREAD

**Issue by DogeTennant** [CodingAir/TradeSystem#327]
When I try to tradelog a player nothing happens and it puts an error into the console

**To Reproduce**
1. /tradelog a player
2. check console

**Expected behavior**
I want to see a history of player's trades

```
[19:11:28 WARN]: [TradeSystem] Plugin TradeSystem v2.0.4 generated an exception while executing task 4946
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.connection" is null
        at de.codingair.tradesystem.spigot.extras.tradelog.repository.adapters.MysqlTradeLogRepository.getLogMessages(MysqlTradeLogRepository.java:43) ~[TradeSystem_v2.0.4.jar:?]
        at de.codingair.tradesystem.spigot.extras.tradelog.TradeLogService.getLogMessages(TradeLogService.java:44) ~[TradeSystem_v2.0.4.jar:?]
        at de.codingair.tradesystem.spigot.extras.tradelog.commands.TradeLogCMD$2.lambda$runCommand$0(TradeLogCMD.java:64) ~[TradeSystem_v2.0.4.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-151]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-151]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

1.17.1 paper

**Discord contact**: DogeTennant#6710

**Comment by CodingAir** [comment]
You don't have an established SQL connection. Check your config and the startup log of TradeSystem.
