### ISSUE TITLE
Spawner bug

### ISSUE THREAD

**Issue by xPoyraz** [CodingAir/TradeSystem#374]
Spawner does not appear on the opposite side
Server version 1.16.5
Discord contact: Poyraz#3391

https://imgur.com/hDMMaFS
https://imgur.com/Xq51BMS

```
[16:45:34] [Server thread/WARN]: [TradeSystem] Plugin TradeSystem v2.1.0_Hotfix-1 generated an exception whilst handling plugin message
java.lang.RuntimeException: java.io.UTFDataFormatException: malformed input around byte 0
	at de.codingair.tradesystem.spigot.transfer.handlers.TradeItemUpdatePacketHandler.process(TradeItemUpdatePacketHandler.java:30) ~[?:?]
	at de.codingair.tradesystem.spigot.transfer.handlers.TradeItemUpdatePacketHandler.process(TradeItemUpdatePacketHandler.java:18) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.DataHandler.receive(DataHandler.java:187) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.variants.bytestream.OneWayStreamDataHandler.receive(OneWayStreamDataHandler.java:63) ~[?:?]
	at de.codingair.tradesystem.spigot.transfer.SpigotHandler.onPluginMessageReceived(SpigotHandler.java:59) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3236) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.UTFDataFormatException: malformed input around byte 0
	at java.io.DataInputStream.readUTF(DataInputStream.java:662) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$8.read(SerializedGeneric.java:180) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$8.read(SerializedGeneric.java:172) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic.read(SerializedGeneric.java:323) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$CollectionHandler.read(SerializedGeneric.java:449) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$CollectionHandler.read(SerializedGeneric.java:423) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic.read(SerializedGeneric.java:323) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$MapHandler.read(SerializedGeneric.java:358) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$MapHandler.read(SerializedGeneric.java:326) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic.read(SerializedGeneric.java:323) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$MapHandler.read(SerializedGeneric.java:358) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic$MapHandler.read(SerializedGeneric.java:326) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric$Generic.read(SerializedGeneric.java:323) ~[?:?]
	at de.codingair.tradesystem.lib.packetmanagement.utils.SerializedGeneric.getObject(SerializedGeneric.java:51) ~[?:?]
	at de.codingair.tradesystem.proxy.packets.TradeItemUpdatePacket.getItem(TradeItemUpdatePacket.java:65) ~[?:?]
	at de.codingair.tradesystem.spigot.transfer.handlers.TradeItemUpdatePacketHandler.process(TradeItemUpdatePacketHandler.java:27) ~[?:?]
	... 20 more
```

**Comment by CodingAir** [comment]
Fixed with #380
